# Uncomment the next line to define a global platform for your project
# platform :ios, '10.6'

target 'Dish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dish

# Firebase
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

# Facebook
pod 'FBSDKLoginKit'

end

